### ISSUE TITLE
Tests seems broken, need to freeze deps version

### ISSUE THREAD

**Issue by sairion** [cujojs/promise-perf-tests#10]
Due to jsdom's breaking API change, this line:

https://github.com/cujojs/promise-perf-tests/blob/f3829a33a5463b1f33c19d41996e9c20338dce8f/lib/adapters/jquery.js#L2

won't work. Changing to `global.window = require("jsdom").jsdom().defaultView` helps, according to [this](http://stackoverflow.com/questions/26492552/jsdom-jsdom-missing-a-createwindow-method).. 

But there is more handful of errors occur after this fix. Seems like `runTest` function doesn't get libs' promise constructor properly, but I have no time looking into this...

IMO most of these problems come from [not specifying version of deps](https://github.com/cujojs/promise-perf-tests/blob/master/package.json). I wish I have more time to look into this ;) A lots of tests against the promise libraries left broken!

**Comment by briancavalier** [comment]
@sairion This project is no longer maintained.  I apologize for not updating the README to indicate that.  I'll do that now.

**Comment by briancavalier** [comment]
Closed by ca23ca3168ee5b5e412edc458d686d67282752c4
