### ISSUE TITLE
Perf tests as an optimization aid

### ISSUE THREAD

**Issue by novemberborn** [cujojs/promise-perf-tests#8]
From <https://github.com/cujojs/promise-perf-tests/pull/6#discussion_r2570609>

> The intent was never to provide a tool for measuring one library's performance or as an optimization helper during development. The intent was always to provide a ballpark comparison between libraries. 

That's fair, but  we do need tools to measure and *optimize* performance. It's [Benchmark Driven Development](https://github.com/felixge/faster-than-c).

This test suite would be perfect for such optimization.

**Comment by briancavalier** [comment]
This project is no longer maintained.
